#!/bin/sh

ETH=${1:-eth0}
shift
STATIC_ARGS="$*"
LINK_UP_TIMEOUT=${LINK_UP_TIMEOUT:-6}
DSCRIPT=/usr/share/udhcpc/default.script
UPID=/tmp/udhcpd.pid
KILLDONE=/tmp/killdone


if [ $LINK_UP_TIMEOUT -gt 999 ]; then
	wait_dev=0
	report_dev=0
	while [ ! -e /sys/class/net/${ETH} ]; do
		sleep 2
		wait_dev=$(($wait_dev+2))		
		report_dev=$((report_dev+1))
		if [ $report_dev -ge 10 ]; then
			echo "NET: wait_dev $ETH $wait_dev.."
			report_dev=0
		fi
	done
fi



start_eth() {
	if [ ! -e /sys/class/net/${ETH} ]; then
		echo "NOTICE: /sys/class/net/${ETH} backgrounding.."
		LINK_UP_TIMEOUT=99999 /etc/network/default-networkrc $ETH $STATIC_ARGS &
		exit
	fi
        ifconfig ${ETH} up

	timer=$LINK_UP_TIMEOUT
	stime=1
        while [ $timer -gt 0 ]; do
                grep -q "up" /sys/class/net/${ETH}/operstate 
                        if [ $? == 0 ]; then
                                echo "ethernet link up"
				return
                        else
                                echo "Waiting for link up ... $timer"
				sleep $stime
                                if [ $LINK_UP_TIMEOUT -le 10 ]; then 
                                	stime=$((stime+1))
                                else                                	
                                	[ $stime -lt 60 ] && stime=$((stime*2))
                                fi
                                let timer=$timer-1
                        fi
        done
	echo "NOTICE: /sys/class/net/${ETH} no link, backgrounding.."
	LINK_UP_TIMEOUT=999 /etc/network/default-networkrc $ETH $STATIC_ARGS &
	exit
}

get_mac_address() {
	cat /sys/class/net/${ETH}/address
}

dhcp_killer() {
	sleep 5
	let countdown=10
	while [ $countdown -gt 0 ]; do
		echo +++ dhcp_killer counting $countdown
		let countdown=$countdown-1
		sleep 1
	done
	echo +++ dhcp_killer ...
	if [ -e $UPID ]; then
		KPID=$(cat $UPID)
		rm $UPID
		kill -9 $KPID
		echo dhcp_killer kill $KPID
		echo dhcp_killer kill $KPID >$KILLDONE
	fi
	MAC=$(get_mac_address)
	let DMINOR=$(printf "%d" 0x$(echo ${MAC##*:}))
	let IPMINOR="$DMINOR==200? 200: $DMINOR%200"
	IP=192.168.0.$IPMINOR
	echo +++ setting fallback static ip $IP
	ifconfig ${ETH} $IP up
}
start_eth

if [ "$*" = "" ]; then
	echo "+++ Starting dhcp daemon [default]"
	dhcp_killer & killer_pid=$!
	udhcpc -i $ETH -q -s $DSCRIPT -x hostname:$(hostname) -p $UPID
	if [ $? -ne 0 ]; then
		echo +++ udhcpc fail, quit
		exit 1
	elif [ -e $KILLDONE ];then
		echo +++ udhcpc fail, $KILLDONE detected
		rm $KILLDONE
		exit 1
	else
		kill -9 $killer_pid
		echo +++ dhcp good, remove failsafe $killer_pid
	fi
	udhcpc -i $ETH -b -a -s/usr/share/udhcpc/default.script  \
                -x hostname:$(hostname) -p /var/run/udhcpc.${ETH}.pid
	source /tmp/dhcp.env
else
	echo "NET: $ETH set static ip $STATIC_ARGS"
	ifconfig $ETH $STATIC_ARGS
fi


if [ -e /mnt/local/ntpd.conf ]; then
	/mnt/local/ntpd.conf
elif [ "x$ntpsrv" != "x" ]; then
	ntpd -p $ntpsrv
elif [ "x$siaddr" != "x" ]; then
        ntpd -p $siaddr
elif [ "x$serverid" != "x" ]; then
        ntpd -p $serverid
fi

